[package]
edition = "2018"
name = "mozrunner"
version = "0.15.0"
authors = ["Mozilla"]
description = "Reliable Firefox process management."
keywords = [
    "firefox",
    "mozilla",
    "process-manager",
]
license = "MPL-2.0"
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/mozbase/rust/mozrunner"

[dependencies]
log = "0.4"
mozprofile = { path = "../mozprofile", version = "0.9" }
plist = "1.0"

[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.5"

[target.'cfg(target_os = "macos")'.dependencies]
dirs = "4"

[[bin]]
name = "firefox-default-path"
