#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

from typing import Dict, Optional


SUPPORTED_NDK_VERSION = '28'
API_LEVEL = '30'


def get_prebuilt_folder_name() -> str:
    os_type = platform.system().lower()
    if os_type not in ["linux", "darwin"]:
        raise Exception("Android cross builds are only supported on Linux and macOS.")

    cpu_type = platform.machine().lower()
    host_suffix = "unknown"
    if cpu_type in ["i386", "i486", "i686", "i768", "x86"]:
        host_suffix = "x86"
    elif cpu_type in ["x86_64", "x86-64", "x64", "amd64"]:
        host_suffix = "x86_64"
    # There are no arm64 prebuilt versions of LLVM available, so
    # we need to force x86_64 (which run via rosetta)
    if os_type == "darwin":
        host_suffix = "x86_64"
    return os_type + "-" + host_suffix

def check_output(*args, **kwargs) -> str:
    return subprocess.check_output(*args, **kwargs).decode("utf-8").strip()


def get_target_from_args() -> str:
    for arg in sys.argv:
        if arg.startswith("--target="):
            return arg.replace("--target=", "")
    print("Error: --target not found in args. Note: You must use `--target=<target>` syntax")
    sys.exit(1)


def set_toolchain_binaries_in_env(toolchain_name: str, toolchain_dir: str, target_triple: str, env: Dict[str, str]):
    cc = os.path.join(toolchain_dir, "bin", f"{toolchain_name}-clang")
    cxx = os.path.join(toolchain_dir, "bin", f"{toolchain_name}-clang++")
    linker = os.path.join(toolchain_dir, "bin", f"{toolchain_name}-clang++")
    ar = check_output([cc, "--print-prog-name=llvm-ar"])
    objcopy = check_output([cc, "--print-prog-name=llvm-objcopy"])
    ranlib = check_output([cc, "--print-prog-name=llvm-ranlib"])
    strip = check_output([cc, "--print-prog-name=llvm-strip"])
    yasm = check_output([cc, "--print-prog-name=yasm"])
    host_cc = env.get('HOST_CC') or shutil.which("clang") or shutil.which("gcc")
    host_cxx = env.get('HOST_CXX') or shutil.which("clang++") or shutil.which("g++")

    assert(host_cc)
    assert(host_cxx)

    target_triple_underscore = target_triple.upper().replace('-', '_')
    env[f'CARGO_TARGET_{target_triple_underscore}_LINKER'] = linker

    env["AR"] = ar
    env["CC"] = cc
    env["CPP"] = f"{cc} -E"
    env["CXX"] = cxx
    env["HOST_CC"] = host_cc
    env["HOST_CXX"] = host_cxx
    env["OBJCOPY"] = objcopy
    env["RANLIB"] = ranlib
    env["STRIP"] = strip
    env["YASM"] = yasm
    env["CLANG_PATH"] = cc
    env["LIBCLANG_PATH"] = os.path.join(toolchain_dir, "lib")
    env["BINDGEN_EXTRA_CLANG_ARGS"] = f"--target={toolchain_name} --sysroot={os.path.join(toolchain_dir, 'sysroot')}"


def create_environment_for_build() -> Dict[str, str]:
    env = os.environ.copy()
    if "ANDROID_NDK_ROOT" not in env:
        raise Exception("Please set the ANDROID_NDK_ROOT environment variable.")

    ndk_home_dir = env["ANDROID_NDK_ROOT"]

    # Check if the NDK version is 21
    if not os.path.isfile(os.path.join(ndk_home_dir, 'source.properties')):
        raise Exception(
            "ANDROID_NDK should have file `source.properties`.\n" +
            "The environment variable ANDROID_NDK_ROOT may be set at a wrong path."
        )

    with open(os.path.join(ndk_home_dir, 'source.properties'), encoding="utf8") as ndk_properties:
        version_found = ndk_properties.readlines()[1].split(' = ')[1].split('.')[0] 
        if version_found != SUPPORTED_NDK_VERSION:
            raise Exception(
                "Servo and dependencies currently only support NDK version " +
                f"{SUPPORTED_NDK_VERSION}. Found {version_found}"
            )

    # Add the toolchain to the path.
    prebuilt_host_arch = get_prebuilt_folder_name()
    toolchain_dir = os.path.join(ndk_home_dir, "toolchains", "llvm", "prebuilt", prebuilt_host_arch)
    env['PATH'] = os.pathsep.join([os.path.join(toolchain_dir, "bin"), env["PATH"]])

    toolchains_for_targets = {
        "armv7-linux-androideabi": "armv7a-linux-androideabi",
        "aarch64-linux-android": "aarch64-linux-android",
        "x86_64-linux-android": "x86_64-linux-android",
    }
    target_triple = get_target_from_args()
    toolchain_name = toolchains_for_targets[target_triple] + API_LEVEL
    set_toolchain_binaries_in_env(toolchain_name, toolchain_dir, target_triple, env)

    # This environment variable is only used by the mozjs build.
    env["ANDROID_API_LEVEL"] = API_LEVEL

    return env

if __name__ == "__main__":
    completed_process = subprocess.run(sys.argv[1:], env=create_environment_for_build())
    sys.exit(completed_process.returncode)
