#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

print("Info: The `ohos-build` script has been replaced with the `cargo ohos` command.")
print("This script will be removed in the future.")
print("You can install it by running `cargo install cargo-ohos` and build by running `cargo ohos build`.")
