schema: 1

bugzilla:
  product: Core
  component: "General"

origin:
  name: rlbox_wasm2c_sandbox
  description: rlbox integration for the wasm2c sandboxed code
  url: https://github.com/PLSysSec/rlbox_wasm2c_sandbox/tree/upstream-wasm2c

  release: 5f2573e2203169b1a3e728a6d612fb78429e1cb8 (2025-03-19T02:22:06Z).
  revision: 5f2573e2203169b1a3e728a6d612fb78429e1cb8

  license: MIT
  license-file: LICENSE

vendoring:
  url: https://github.com/PLSysSec/rlbox_wasm2c_sandbox
  source-hosting: github
  vendor-directory: third_party/rlbox_wasm2c_sandbox

  exclude:
    # dirs
    - test
    # files
    - ".*"
    - AppSandbox.md
    - CMakeLists.txt
    - LibrarySandbox.md
    - README.md
    - build-wasiclang.sh
