// Generated by make_intl_data.py. DO NOT EDIT.
// Version: 2026-01-01

/**
 * Mapping from currency codes to the number of decimal digits used for them.
 * Default is 2 digits.
 *
 * Spec: ISO 4217 Currency and Funds Code List.
 * http://www.currency-iso.org/en/home/tables/table-a1.html
 */

#ifndef builtin_intl_CurrencyDataGenerated_h
#define builtin_intl_CurrencyDataGenerated_h

#define CURRENCIES_WITH_NON_DEFAULT_DIGITS(MACRO)         \
  /* Bahraini Dinar (BAHRAIN) */                          \
  MACRO(BHD, 3)                                           \
  /* Burundi Franc (BURUNDI) */                           \
  MACRO(BIF, 0)                                           \
  /* Unidad de Fomento (CHILE) */                         \
  MACRO(CLF, 4)                                           \
  /* Chilean Peso (CHILE) */                              \
  MACRO(CLP, 0)                                           \
  /* Djibouti Franc (DJIBOUTI) */                         \
  MACRO(DJF, 0)                                           \
  /* Guinean Franc (GUINEA) */                            \
  MACRO(GNF, 0)                                           \
  /* Iraqi Dinar (IRAQ) */                                \
  MACRO(IQD, 3)                                           \
  /* Iceland Krona (ICELAND) */                           \
  MACRO(ISK, 0)                                           \
  /* Jordanian Dinar (JORDAN) */                          \
  MACRO(JOD, 3)                                           \
  /* Yen (JAPAN) */                                       \
  MACRO(JPY, 0)                                           \
  /* Comorian Franc  (COMOROS (THE)) */                   \
  MACRO(KMF, 0)                                           \
  /* Won (KOREA (THE REPUBLIC OF)) */                     \
  MACRO(KRW, 0)                                           \
  /* Kuwaiti Dinar (KUWAIT) */                            \
  MACRO(KWD, 3)                                           \
  /* Libyan Dinar (LIBYA) */                              \
  MACRO(LYD, 3)                                           \
  /* Rial Omani (OMAN) */                                 \
  MACRO(OMR, 3)                                           \
  /* Guarani (PARAGUAY) */                                \
  MACRO(PYG, 0)                                           \
  /* Rwanda Franc (RWANDA) */                             \
  MACRO(RWF, 0)                                           \
  /* Tunisian Dinar (TUNISIA) */                          \
  MACRO(TND, 3)                                           \
  /* Uganda Shilling (UGANDA) */                          \
  MACRO(UGX, 0)                                           \
  /* Uruguay Peso en Unidades Indexadas (UI) (URUGUAY) */ \
  MACRO(UYI, 0)                                           \
  /* Unidad Previsional (URUGUAY) */                      \
  MACRO(UYW, 4)                                           \
  /* Dong (VIET NAM) */                                   \
  MACRO(VND, 0)                                           \
  /* Vatu (VANUATU) */                                    \
  MACRO(VUV, 0)                                           \
  /* CFA Franc BEAC (CAMEROON) */                         \
  /* CFA Franc BEAC (CENTRAL AFRICAN REPUBLIC (THE)) */   \
  /* CFA Franc BEAC (CHAD) */                             \
  /* CFA Franc BEAC (CONGO (THE)) */                      \
  /* CFA Franc BEAC (EQUATORIAL GUINEA) */                \
  /* CFA Franc BEAC (GABON) */                            \
  MACRO(XAF, 0)                                           \
  /* CFA Franc BCEAO (BENIN) */                           \
  /* CFA Franc BCEAO (BURKINA FASO) */                    \
  /* CFA Franc BCEAO (CÔTE D'IVOIRE) */                   \
  /* CFA Franc BCEAO (GUINEA-BISSAU) */                   \
  /* CFA Franc BCEAO (MALI) */                            \
  /* CFA Franc BCEAO (NIGER (THE)) */                     \
  /* CFA Franc BCEAO (SENEGAL) */                         \
  /* CFA Franc BCEAO (TOGO) */                            \
  MACRO(XOF, 0)                                           \
  /* CFP Franc (FRENCH POLYNESIA) */                      \
  /* CFP Franc (NEW CALEDONIA) */                         \
  /* CFP Franc (WALLIS AND FUTUNA) */                     \
  MACRO(XPF, 0)

#endif  // builtin_intl_CurrencyDataGenerated_h
