// Generated by make_intl_data.py. DO NOT EDIT.

#ifndef builtin_intl_MeasureUnitGenerated_h
#define builtin_intl_MeasureUnitGenerated_h

namespace js::intl {

struct SimpleMeasureUnit {
  const char* const name;
};

/**
 * The list of currently supported simple unit identifiers.
 *
 * The list must be kept in alphabetical order.
 */
inline constexpr SimpleMeasureUnit simpleMeasureUnits[] = {
    // clang-format off
  {"acre"},
  {"bit"},
  {"byte"},
  {"celsius"},
  {"centimeter"},
  {"day"},
  {"degree"},
  {"fahrenheit"},
  {"fluid-ounce"},
  {"foot"},
  {"gallon"},
  {"gigabit"},
  {"gigabyte"},
  {"gram"},
  {"hectare"},
  {"hour"},
  {"inch"},
  {"kilobit"},
  {"kilobyte"},
  {"kilogram"},
  {"kilometer"},
  {"liter"},
  {"megabit"},
  {"megabyte"},
  {"meter"},
  {"microsecond"},
  {"mile"},
  {"mile-scandinavian"},
  {"milliliter"},
  {"millimeter"},
  {"millisecond"},
  {"minute"},
  {"month"},
  {"nanosecond"},
  {"ounce"},
  {"percent"},
  {"petabyte"},
  {"pound"},
  {"second"},
  {"stone"},
  {"terabit"},
  {"terabyte"},
  {"week"},
  {"yard"},
  {"year"},
    // clang-format on
};

}  // namespace js::intl

#endif
