[package]
edition = "2018"
name = "mozversion"
version = "0.5.0"
authors = ["Mozilla"]
description = "Utility for accessing Firefox version metadata"
keywords = [
    "firefox",
    "mozilla",
]
license = "MPL-2.0"
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/mozbase/rust/mozversion"

[dependencies]
regex = { version = "1", default-features = false, features = ["perf", "std"] }
rust-ini = "0.10"
semver = "1.0"
