[package]
license = "MPL-2.0"
description = "copy of locale_glue for mozjs-sys"
links = "locale_glue"
repository = "https://github.com/servo/mozjs"
name = "mozjs_locale_glue"
version = "153.2.0.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
icu_locale = { version = "2.1.1", features = ["compiled_data"] }

[build-dependencies.cbindgen]
version = "0.29.4"
