[package]
edition = "2018"
name = "mozdevice"
version = "0.5.0"
authors = ["Mozilla"]
description = "Client library for the Android Debug Bridge (adb)"
keywords = [
    "adb",
    "android",
    "firefox",
    "geckoview",
    "mozilla",
]
license = "MPL-2.0"
repository = "https://hg.mozilla.org/mozilla-central/file/tip/testing/mozbase/rust/mozdevice"

[dependencies]
log = { version = "0.4", features = ["std"] }
once_cell = "1.4.0"
regex = { version = "1", default-features = false, features = ["perf", "std"] }
tempfile = "3"
thiserror = "1.0.25"
walkdir = "2"
unix_path = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

