[package]
name = "mozjs_sys"
description = "System crate for the Mozilla SpiderMonkey JavaScript engine."
repository.workspace = true
version = "153.0.0-1"
authors = ["Mozilla", "The Servo Project Developers"]
links = "mozjs"
license.workspace = true
exclude = ["__pycache__", "/etc/", "/mozjs/.cargo/"]
edition.workspace = true

[lib]
name = "mozjs_sys"
# The generated jsapi.rs contains #[doc] strings which look like
# doctests but are definitely not.
doctest = false

[features]
debugmozjs = []
profilemozjs = []
jit = []
jitspew = []
libz-sys = ["dep:libz-sys"]
libz-rs = ["dep:libz-rs-sys"]
intl = [
  "dep:icu_capi",
  "dep:mozjs_unicode_bidi_ffi",
  "dep:mozjs_properties_glue",
  "dep:mozjs_collator_glue",
  "dep:mozjs_locale_glue",
]
crown = []
oom_with_hook = []

[dependencies]
libc.workspace = true

# In SM these dependencies provided via jsrust_shared crate
# https://github.com/mozilla-firefox/firefox/blob/main/js/src/rust/shared/Cargo.toml
# which links to SM.
# Cargo does not allow recursive invocations so we link to them from here.

encoding_c = "0.9.8"
encoding_c_mem = "0.2.6"
# keep in sync with intl/icu_capi/Cargo.toml
icu_capi = { version = "=2.1.2", default-features = false, features = [
  "any_provider",
  "compiled_data",
  "segmenter",
  "calendar",
], optional = true }
mozjs_unicode_bidi_ffi = { version = "=153.0.0", path = "../mozjs-extracted-crates/unicode_bidi_ffi", optional = true }
mozjs_normalizer_glue = { version = "=153.0.0", path = "../mozjs-extracted-crates/normalizer_glue" }
mozjs_properties_glue = { version = "=153.0.0", path = "../mozjs-extracted-crates/properties_glue", optional = true }
mozjs_collator_glue = { version = "=153.0.0", path = "../mozjs-extracted-crates/collator_glue", optional = true }
mozjs_locale_glue = { version = "=153.0.0", path = "../mozjs-extracted-crates/locale_glue", optional = true }

libz-rs-sys = { version = "0.6", features = [
  "export-symbols",
], optional = true }
libz-sys = { version = "1.1.19", default-features = false, features = [
  "libc",
  "stock-zlib",
], optional = true }

[build-dependencies]
bindgen.workspace = true
cc.workspace = true
walkdir = "2"
flate2 = "1"
tar = "0.4"
