[package]
license = "MPL-2.0"
description = "copy of collator_glue for mozjs-sys"
links = "collator_glue"
repository = "https://github.com/servo/mozjs"
name = "mozjs_collator_glue"
version = "153.0.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
icu_collator = { package = "mozjs_icu_collator", version = "=153.0.0", path = "../icu_collator", features = ["latin1", "compiled_data", "unstable"] }
icu_locale_core = "2.1.1"
tinystr = { version = "0.8.0", default-features = false }
arraystring = "0.3.0"
writeable = { version = "0.6.0", default-features = false }
arrayvec = "0.7"

[build-dependencies.cbindgen]
version = "0.29.4"
