[DEFAULT]

["perftest_WPT_chrome_init_file.js"]

["perftest_WPT_firefox_init_file.js"]

["perftest_bbc_link.js"]

["perftest_facebook.js"]

["perftest_jsconf_cold.js"]

["perftest_jsconf_warm.js"]

["perftest_pageload.js"]

["perftest_perfstats.js"]

["perftest_politico_link.js"]

["perftest_youtube_link.js"]
