#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ifndef NO_DIST_INSTALL

ifneq (,$(strip $(SIMPLE_PROGRAMS)))
PROGRAMS_EXECUTABLES = $(SIMPLE_PROGRAMS)
PROGRAMS_DEST ?= $(FINAL_TARGET)
PROGRAMS_TARGET := target
INSTALL_TARGETS += PROGRAMS
endif

ifneq (,$(strip $(RUST_PROGRAMS)))
RUST_PROGRAMS_EXECUTABLES = $(RUST_PROGRAMS)
RUST_PROGRAMS_DEST ?= $(FINAL_TARGET)
RUST_PROGRAMS_TARGET := $(or $(RUST_PROGRAM_OUTPUT_CATEGORY),target)
INSTALL_TARGETS += RUST_PROGRAMS
endif

ifneq (,$(strip $(HOST_SIMPLE_PROGRAMS)))
HOST_PROGRAMS_EXECUTABLES = $(HOST_SIMPLE_PROGRAMS)
HOST_PROGRAMS_DEST ?= $(DIST)/host/bin
HOST_PROGRAMS_TARGET = host
INSTALL_TARGETS += HOST_PROGRAMS
endif

ifneq (,$(strip $(HOST_RUST_PROGRAMS)))
HOST_RUST_PROGRAMS_EXECUTABLES = $(HOST_RUST_PROGRAMS)
HOST_RUST_PROGRAMS_DEST ?= $(DIST)/host/bin
HOST_RUST_PROGRAMS_TARGET = $(or $(HOST_RUST_PROGRAM_OUTPUT_CATEGORY),host)
INSTALL_TARGETS += HOST_RUST_PROGRAMS
endif

endif # !NO_DIST_INSTALL

# EOF
