name: Security bump

on:
    workflow_dispatch:
    schedule:
        # Runs at 03:30, every Saturday
        - cron: "30 3 * * 3"

jobs:
    bump:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
            - run: pip install requests
            - run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
            - run: python3 ./mozjs-sys/etc/sm-security-bump.py
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
